return {
	typex      = require("core.typex"),
	tablex     = require("core.tablex"),
	stringx    = require("core.stringx"),
	mathx      = require("core.mathx"),
	iterx      = require("core.iterx"),
	oopx       = require("core.oopx"),
	coroutinex = require("core.coroutinex"),
	eventx     = require("core.eventx"),
	taskx      = require("core.taskx"),
	assertx    = require("core.assertx"),
	asyncx     = require("core.asyncx"),
	pair       = require("core.pair"),
	rect       = require("core.rect"),
	set        = require("core.set"),
	vector2    = require("core.vector2"),
	vector3    = require("core.vector3"),
	vector4    = require("core.vector4"),
}
